FROM node:20

WORKDIR /app

COPY package.json /app/package.json

RUN npm i

RUN npm i -g @angular/cli@latest

COPY . .

CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--disable-host-check"]
