services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules/
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
  service:
    build:
      context: ./services
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    ports:
      - '9229:9229' # Debug Port
    volumes:
      - /app/node_modules
      - ./services:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
  redis:
    image: 'redis:7.2.5'
  postgres:
    image: 'postgres:16.3'
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d thebus -h localhost']
      interval: 3s
      timeout: 1s
      retries: 10
    environment:
      - POSTGRES_DB=thebus
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust # TODO: For the health check to work without password. I'm sure there is a
        # good way to do this.
