services:
  frontend:
    build:
      context: ./frontend
    environment:
      - NODE_ENV=production
    ports:
      - 9080:80
    depends_on:
      backend:
        condition: service_started
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
  queue-manager:
    build:
      context: ./services/manager
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
  worker-bus-api:
    build:
      context: ./services/workers/worker-bus-api
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
  redis:
    image: 'redis:7.2.5'
  postgres:
    image: 'postgres:16.3'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=thebus
      - POSTGRES_USER=admin
      - POSTGRES_HOST_AUTH_METHOD=trust # TODO: For the health check to work without password. I'm sure there is a
        # good way to do this.
