FROM python:3.12-slim-bullseye

ENV DIRECT_MODE=true
ENV FORCE_UPDATE=true

WORKDIR /app

COPY . /app

# pip caches all packages. Remove cache to make the image smaller.
RUN pip install --no-cache-dir -r requirements.txt

# CMD watchfiles "python src/gtfsEtl.py" src
CMD watchfiles "python src/main.py --force" src