FROM node:20

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm i

# Install nodemon and ts-node globally
RUN npm install -g nodemon ts-node

# Copy the rest of your application's code
COPY . .

CMD ["nodemon"]