FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm i

# Install nodemon and ts-node globally
RUN npm install -g tsx

# Copy the rest of your application's code
COPY . .

CMD ["npm", "run", "dev"]
# CMD ["tail", "-f" ,"/dev/null"]